<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="bookings.aspx.cs" Inherits="studyRoom.WebForm3" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div>
        <div class="row">
           <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>My Bookings</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <form class="form-horizontal form-label-left" novalidate runat="server">
                            <asp:GridView ID="bookingTableGV" runat="server" CssClass="table table-striped responsive-utilities jambo_table bulk_action" EmptyDataText="" AutoGenerateDeleteButton="true" OnRowDeleting="BookingsGV_RowDeleting"></asp:GridView>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</asp:Content>
